import ComponentProps from '@/types/components/ComponentProps'

export default function PrettyCode({ children }: ComponentProps) {
  return (
    <div className='[&_[data-rehype-pretty-code-figure]]:my-8 [&_[data-rehype-pretty-code-figure]_[data-highlighted-chars]]:rounded [&_[data-rehype-pretty-code-figure]_[data-highlighted-chars]]:bg-signal/20 [&_[data-rehype-pretty-code-figure]_[data-highlighted-chars]]:px-1 [&_[data-rehype-pretty-code-figure]_[data-highlighted-line]]:border-l-signal [&_[data-rehype-pretty-code-figure]_[data-highlighted-line]]:bg-signal/10 [&_[data-rehype-pretty-code-figure]_[data-line]]:border-l-2 [&_[data-rehype-pretty-code-figure]_[data-line]]:border-l-transparent [&_[data-rehype-pretty-code-figure]_[data-line]]:px-4 [&_[data-rehype-pretty-code-figure]_code]:grid [&_[data-rehype-pretty-code-figure]_code]:w-max [&_[data-rehype-pretty-code-figure]_code]:min-w-full [&_[data-rehype-pretty-code-figure]_code]:bg-transparent [&_[data-rehype-pretty-code-figure]_code]:p-0 [&_[data-rehype-pretty-code-figure]_code]:font-mono [&_[data-rehype-pretty-code-figure]_code]:leading-6 [&_[data-rehype-pretty-code-figure]_pre]:m-0 [&_[data-rehype-pretty-code-figure]_pre]:overflow-x-auto [&_[data-rehype-pretty-code-figure]_pre]:rounded-xl [&_[data-rehype-pretty-code-figure]_pre]:border [&_[data-rehype-pretty-code-figure]_pre]:border-line [&_[data-rehype-pretty-code-figure]_pre]:bg-elevated [&_[data-rehype-pretty-code-figure]_pre]:py-4 [&_[data-rehype-pretty-code-figure]_pre]:text-sm [&_[data-rehype-pretty-code-figure]_pre]:shadow-editorial [&_[data-rehype-pretty-code-figure]_pre]:dark:shadow-editorial-dark [&_[data-rehype-pretty-code-title]+pre]:rounded-t-none [&_[data-rehype-pretty-code-title]]:rounded-t-xl [&_[data-rehype-pretty-code-title]]:border [&_[data-rehype-pretty-code-title]]:border-b-0 [&_[data-rehype-pretty-code-title]]:border-line [&_[data-rehype-pretty-code-title]]:bg-surface [&_[data-rehype-pretty-code-title]]:px-4 [&_[data-rehype-pretty-code-title]]:py-2 [&_[data-rehype-pretty-code-title]]:font-mono [&_[data-rehype-pretty-code-title]]:text-xs [&_[data-rehype-pretty-code-title]]:font-semibold [&_[data-rehype-pretty-code-title]]:text-muted'>
      {children}
    </div>
  )
}
